name: moneyger_frontend
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.3
  http: ^0.13.4
  flutter_svg: ^1.0.3
  # flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: Lato
    fonts:
    - asset: assets/fonts/Lato-Regular.ttf
    - asset: assets/fonts/Lato-Bold.ttf
  assets:
  - assets/images/

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/logo-big.png"
#   adaptive_icon_background: "#ffffff"
#   adaptive_icon_foreground: "assets/images/logo-big.png"